[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
    "cd backend",
    "python -m venv venv",
    "source venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "chmod +x start.sh && ./start.sh"
