[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
PYTHON_VERSION = "3.11"
